Biografia de Danny Trejo
zinns/HTML-Course pull request #13
Opened 2023-09-22 04:39 UTC by davidTocineta

2023-09-22 04:52 UTC, soyedgarzea requested changes

2023-10-06 04:08 UTC, andysotocruz approved these changes

2023-10-13 03:24 UTC, eamzea requested changes

2023-10-13 03:24 UTC, eamzea commented on 02/index.html
> +         <p> Nombre: Danny Trejo </p>
Esta línea no está indentada

2023-10-13 03:40 UTC, davidTocineta commented on 02/index.html
> +         <p> Nombre: Danny Trejo </p>
este comentario ya fue resuelto

2023-10-13 03:41 UTC, eamzea approved these changes

2023-10-13 03:41 UTC, merged