html autobiography info added
zinns/HTML-Course pull request #19
Opened 2023-10-18 02:31 UTC by abrilmunozc

2023-10-18 02:52 UTC, eamzea requested changes

2023-10-18 02:52 UTC, eamzea commented on 02/index.html
> +    <title>Document</title>
This is the title of the file?

2023-10-18 02:52 UTC, eamzea commented on 02/index.html
> +    <title>Document</title>
Where is the meta tag we already saw?

2023-10-18 02:52 UTC, eamzea commented on 02/index.html
> +    <p><h1><strong>My autobiography</strong></h1></p>
Why a strong tag inside an h1 tag inside a p tag?

2023-10-18 02:52 UTC, eamzea commented on 02/index.html
> +</p>
All this text inside a single paragraph?

2023-10-19 01:44 UTC, abrilmunozc commented on 02/index.html
> +    <title>Document</title>
I don't understand the question

2023-10-19 03:10 UTC, eamzea requested changes

2023-10-19 03:10 UTC, eamzea commented on 02/index.html
> +    <p><h2>Name: <em>Abril Muñoz</em></h2></p>
Why a heading should be inside a paragraph?

2023-10-19 03:10 UTC, eamzea commented on 02/index.html
> +
I guess you can improve the readability of this short code.

2023-10-26 04:33 UTC, eamzea approved these changes

2023-10-26 04:33 UTC, merged