feat song vete de una vez added
zinns/HTML-Course pull request #29
Opened 2023-11-08 02:54 UTC by abrilmunozc

2023-11-08 02:57 UTC, andysotocruz reviewed
where is the nav?

2023-11-08 02:57 UTC, andysotocruz commented on 03/index.html
> +    <div></div>
why is there an empty div?

2023-11-08 02:57 UTC, andysotocruz commented on 03/index.html
> +      <h6>
why are there p tags inside an h6?

2023-11-08 02:59 UTC, andysotocruz commented on 03/index.html
> +  <meta name="keywords" content="daniela, spalla, vete, vez, cancion">
there is an error in the content

2023-11-08 03:03 UTC, eamzea requested changes

2023-11-08 03:03 UTC, eamzea commented on 03/index.html
> +    <footer>
Why main is not the main tag in this document?
If you have more doubts, take a look at this link https://dev.to/sapardo/etiquetas-semanticas-de-html5-3j7m

2023-11-08 03:39 UTC, andysotocruz reviewed
again, where is the nav?

2023-11-08 03:53 UTC, andysotocruz submitted a review, later dismissed

2023-11-08 04:04 UTC, andysotocruz commented on 03/index.html
> +    </header>
Indentation.

2023-11-10 18:06 UTC, soyedgarzea requested changes
Conflicts in the branch

2023-11-17 03:00 UTC, eamzea requested changes

2023-11-17 03:00 UTC, eamzea commented on 03/index.html
> +      <h1>lovely</h1>
There should be only one h1 inside the html file

2023-11-20 18:45 UTC, soyedgarzea requested changes

2023-11-20 18:45 UTC, eamzea commented on 03/index.html
> +  </article>
Looks like here was a indentation issue

2023-11-22 02:32 UTC, eamzea approved these changes

2023-11-22 02:32 UTC, merged