feat song first love added
zinns/HTML-Course pull request #30
Opened 2023-11-08 03:15 UTC by abrilmunozc

2023-11-08 03:27 UTC, eamzea requested changes

2023-11-08 03:27 UTC, eamzea commented on 03/index.html
> +</footer>
Indentation

2023-11-08 03:27 UTC, eamzea commented on 03/index.html
> +  </h6>
Paragraphs inside heading tags?

2023-11-08 03:31 UTC, andysotocruz reviewed
where is the nav?

2023-11-08 03:32 UTC, andysotocruz reviewed
are there only p and h tags for texts?

2023-11-08 03:48 UTC, andysotocruz reviewed
again, are there only paragraph and heading tags for text?

2023-11-08 03:48 UTC, eamzea requested changes

2023-11-08 03:48 UTC, eamzea commented on 03/index.html
> +</footer>
Indentation

2023-11-10 18:05 UTC, eamzea requested changes

2023-11-10 18:05 UTC, eamzea commented on 03/index.html
> +  <p><mark>Letra de First Love © Melted Stone Publishing Ltd.</mark></p>
This can be better organized

2023-11-17 02:26 UTC, eamzea submitted a review, later dismissed

2023-11-22 02:46 UTC, eamzea requested changes

2023-11-22 02:46 UTC, eamzea commented on 03/index.html
> +</html>
Why this closing tag is here?

2023-11-22 02:46 UTC, eamzea commented on 03/index.html
>    </main>
I see another closing main tag in line 43

2023-11-22 02:58 UTC, eamzea requested changes

2023-11-22 02:58 UTC, eamzea commented on 03/index.html
> +  <header>Vete de una vez</header>
Plain text inside header tag?

2023-11-22 02:58 UTC, eamzea commented on 03/index.html
> +    <h2>Daniela Spalla</h2>
Indentation

2023-11-22 03:01 UTC, eamzea requested changes

2023-11-22 03:01 UTC, eamzea commented on 03/index.html
> +  <header>Vete de una vez</header>
The same as the last requested change
Is good to have plain text inside a container tag?

2023-11-22 03:06 UTC, eamzea approved these changes

2023-11-22 03:06 UTC, merged